### ISSUE TITLE
Install on OSX

### ISSUE THREAD

**Issue by GITchristoph** [markummitchell/engauge-digitizer#126]
How can I install the software?

I can't find an Installation Guide?

A short explanation would be very much appreciated.

Cheers, Chris

**Comment by markummitchell** [comment]
Hi Chris. I'm still so new to OSX that I don't even know the "official" way to install it. The OSX version was only released a few weeks ago. However, I am looking for an OSX person to help make releases easier. Although there is another github issue related to OSX, this issue is still a good reminder that documentation and process need to be fixed.

**Comment by GITchristoph** [comment]
I need to take back my "issue" tracker because I oversaw the "Releases" Tab inside the "Code" Tab.
There is a compiled *.app file that I can start using right away.
I thought I need to compile it from the github repository myself.

So even for simple users like myself it's very easy to use the engauge-digitzer.

Thanks a lot for this software. it's great!

Chris
