### ISSUE TITLE
strange output on qmake

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#141]
Check this https://ci.appveyor.com/project/markummitchell/engauge-digitizer/build/1.0.187/job/sjc7r7txaw5c698p
```
Project MESSAGE: Build type:       release
Project MESSAGE: JPEG2000 support: no
Project MESSAGE: PDF support:      yes
Project MESSAGE: Build type:       release
Project MESSAGE: JPEG2000 support: no
Project MESSAGE: PDF support:      yes
Project MESSAGE: Build type:       debug
Project MESSAGE: JPEG2000 support: no
Project MESSAGE: PDF support:      yes
```
Repeated several times and the last time build type differs from actual one.

**Comment by markummitchell** [comment]
I'm on vacation, but will be able to look at this soon.

**Comment by markummitchell** [comment]
It looks like qmake really wants to generate 3 files in WIndows: Makefile Makefile.Debug and Makefile.Release. I tried many variations of setting CONFIG and QT options. Instead of trying to change that behavior, I think changing the nmake line to 'nmake release' might fix the problem. In other words, we should be able to force the building of the release version.
