### ISSUE TITLE
Ability to crop image on import

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#149]
Just like with the PDF import - it would be super nice to have the ability to select with rectangle the needed area of image when importing it.

**Comment by markummitchell** [comment]
This could be implemented with a new Main Window flag that could bring up an optional dialog for selecting the image. The flag off would skip the dialog so users preferring the simpler, faster method would be happy, and the regression tests would still work (since modal dialogs interfere). This would not require changing the Document format, so we would not have to go to release 9.
