### ISSUE TITLE
project file debug build detection logic

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#183]
Below are my assumptions based on appveyor builds.
Related to https://github.com/markummitchell/engauge-digitizer/issues/150
I am talking about this line https://github.com/markummitchell/engauge-digitizer/blob/master/engauge.pro#L32 So when I pass CONFIG+="debug pdf" somehow EXE gets linked to release DLLs, but if I pass just CONFIG+="debug" then EXE correctly links to debug DLLs. It is not poppler-qt5.dll which confuses linking process, right?

**Comment by markummitchell** [comment]
I tried 3 cases
1) qmake engauge.pro
2) qmake engauge.pro "CONFIG+=debug"
3) qmake engauge.pro "CONFIG+=debug pdf"
The pattern I saw was that Makefile, Makefile.Debug and Makefile.Release were created in all 3 cases. Without "CONFIG+=debug" the default in Makefile was to call Makefile.Release, otherwise Makefile would call Makefile.Debug. You can override the default using "nmake debug" or "nmake release". 

There is some confusing behavior when running qmake. Both Makefile.debug and Makefile.release are always created, if I remember correctly, even when "CONFIG-=debug" is used. At times the same Makefile.debug or Makefile.release file is created twice in a row (which is strange but does not break anything).

I do not know if this is helpful, but it may help while working on this.

I do not see the  weird behavior you have having with CONFIG+=debug.

**Comment by crayxt** [comment]
@markummitchell yes, as I was suspecting, the poppler-qt5 is pulling release libraries ;) I will provide debug build of it.
![poppler](https://cloud.githubusercontent.com/assets/33132/18823045/653e6872-83cf-11e6-8705-c0245a00a811.JPG)

**Comment by markummitchell** [comment]
Now I understand. By the way, what tool are you using to see the libraries? I am usually  in Linux and am not familiar with Windows tools.

**Comment by crayxt** [comment]
@markummitchell the tool is called depwalker (http://www.dependencywalker.com). I am about to open PR with fixed debug build on appveyor, I added poppler-qt5-debug lib already.

**Comment by markummitchell** [comment]
I just tried Dependency Walker and like it.

Thanks for working on the Windows builds.

**Comment by crayxt** [comment]
@markummitchell you're welcome. BTW, we need to move those libraries for appveyor builds out of my dropbox folder. Any ideas where to put them?

**Comment by markummitchell** [comment]
Maybe a new directory like 'dev/windows/appveyor'. That may be more permanent and/or reliable than moving to my dropbox folder or some equivalent.
