### ISSUE TITLE
Digitizing array of circle with different radius

### ISSUE THREAD

**Issue by MoloTkos** [markummitchell/engauge-digitizer#209]
There is such of type of diagram where the value represent as different size circles:
1. some parameter in different region of map,
2. comparison of some statistic data,
3. measurements of particle size on some microphotos (by TEM, STM).
It can be useful to have method for digitize this type of date manually at first.
![for github tem](https://cloud.githubusercontent.com/assets/20183575/23163114/c608f8d0-f863-11e6-8a44-670110eafcc3.png)
![for github map](https://cloud.githubusercontent.com/assets/20183575/23163118/cd1fa0b0-f863-11e6-8408-cf27d51970a7.png)

**Comment by markummitchell** [comment]
The new version 10, which has not been released yet, supports maps, where each map has a scale bar defining the scale. This new version may be useful since your first diagram has a 200nm scale. The second picture has a problem since its coordinates are not rectangular. For maps, a two-dimensional coordinate system is defined so point coordinates are defined.You can try a Windows version at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master - select RELEASE or DEBUG version, then select Artifacts, then download 7z file. Open the 7z file and run engauge.exe

**Comment by crayxt** [comment]
@markummitchell The appveyor version built with VS2015 didn't work for me, I think because of poppler-qt5 and log4cpp library versions being built with VS 2013. I think we need to revert appveyor to VS2013 for now.

**Comment by crayxt** [comment]
For OP, I think you need to try out builds from maps branch, as Mark suggested, see https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/maps

**Comment by crayxt** [comment]
Mark I reverter master branch back to VS 2013, until I have correct versions of log4cpp and poppler-qt libraries.

**Comment by markummitchell** [comment]
Baurzhan, I will try upgrading to VS2015. It also appears that poppler support was not being built with the Windows releases, so I will try to make sure that does not get overlooked. The poppler version I've been using in Linux is 0.51.

**Comment by crayxt** [comment]
I suggest to drop poppler support for now in Windows appveyor builds. The current version of poppler we are using is linked to old versions of freetype, zlib, cairo; e.g. those libraries are not secure. I have tried to upgrade those, but it requires much effort, so let's postpone it, and upgrade to VS2015.

**Comment by markummitchell** [comment]
The changes required to support circles of different sizes would be extremely complex. I recommend the creation of another tool.

**Comment by markummitchell** [comment]
@OP I think there may be a reasonable solution. During "Import (Advanced)" there could be an option to look for circles. Selecting that would result in an edge detection algorithm, and then a correlation algorithm to rank matches as a function of coordinates (x,y) and radius (r). The matches would be sorted and then added as points in order of best match to worst match. The ranking helps since the user can apply Undo to remove matches in reverse order (worst match to best match) until reaching the level where the matches are "good enough".

**Comment by markummitchell** [comment]
I created a python script (contrib/python/find_circles.py) in the 'pointload' branch that finds the center of circles and generates a csv file that can be imported into Engauge using a new 'Import (Sorted Points)' command. 

Comments:
1) the algorithm creates a lot of false points in the legend area so the legend region must be skipped (not implemented in code yet)
2) the script takes a very long time to run
3) images that would benefit from this new capability seem to be Maps rather than Graphs
4) Many Map images seem to have projections in which the longitude and latitude lines are not orthogonal, which is incompatible with Engauge without preprocessing to make those lines orthogonal.

At this point, I am wondering if anybody would benefit from an algorithm that finds circles of various radii. Circles with a single radius can be found using Point Match.

Comments?

**Comment by markummitchell** [comment]
Although the preprocessing solution worked, very slowly, once the points get into Engauge then the lack of support for (1) variable-sized point matching and (2) assistance in centering makes it very hard to continue. This effort will be halred for now
