### ISSUE TITLE
Too little grid lines in X-direction

### ISSUE THREAD

**Issue by dirixmjm** [markummitchell/engauge-digitizer#244]
I have set three axis points, (0,0), (0,2) and (33,0).
Then I have set the Grid Display to:
X Grid Lines: Start 0, Step: 1, Stop 33
Y Grid Lines: Start 0, Step 0.2, Stop 2

Then I find that in Y-direction there are 11 Grid lines (including 0 and 2) which is correct.
But In X-Direction there are only 25 Grid lines instead of 33, and the grid line positions don't match the correct locations on the graph. 

As a result, I think the output is also wrong.
Engauge version 10.3

(I am unable to upload the engauge file itself).
![grid](https://user-images.githubusercontent.com/553188/31167402-37e0e1c2-a8f2-11e7-9ee8-45614b7cf4c5.PNG)
![axispoint](https://user-images.githubusercontent.com/553188/31167410-3e042e56-a8f2-11e7-9ffa-4d63a768759f.PNG)
![gridsettings](https://user-images.githubusercontent.com/553188/31167415-4228be20-a8f2-11e7-80dc-d2d0817b10b0.PNG)

**Comment by markummitchell** [comment]
There is a maximum limit to the number of grid lines that is set in Settings / Main Window. That limit is need to prevent (near or complete) infinite loops due to step sizes that are too small (due to switching between linear/log modes). I have made a few changes to address this problem: (1) increase default from 25 to 100 so fewer people even encounter the limit, (2) If the limit will be a problem when editing the grid line settings, give a warning so users are informed and understand that there is a limit.

A quick fix for the version you have is to increase the maximum number of grid lines in Settings / Main Window.

**Comment by markummitchell** [comment]
You can try out the changes in Windows from https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/8tsuh30xkm7e67ha/artifacts for 32 bits, and https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/0cbkkrdtunkl7qip/artifacts for 64 bits.

**Comment by dirixmjm** [comment]
Setting the maximum number of grid lines to 100 works for me.

Thanks!

**Comment by markummitchell** [comment]
I agree. Fixed. It is less confusing now.
