### ISSUE TITLE
Program crashes opening some dig files.

### ISSUE THREAD

**Issue by k1moradi** [markummitchell/engauge-digitizer#273]
The link below is a dig file that I tried to open with several versions of the program including the latest 10.8 version and I faced a nasty crash.
https://drive.google.com/open?id=0B_E22hBpxj_VRi1ySVZLTndleUE

**Comment by markummitchell** [comment]
Thanks for the information. I will look into this today.

**Comment by markummitchell** [comment]
That file appears to be from version 4.1. The code currently only accepts version 5 and newer. I can probably add support for version 4.X fairly quickly.

**Comment by markummitchell** [comment]
The dig file having a problem getting read was many years old, and was version 4.1. This should not be a common problem. The issue was that the grid removal settings seemed to be set randomly, leading to unrealistic values like a billion grid lines. The fix was to initialize the grid removal settings to the grid display settings if invalid grid removal settings were encountered. There is a pre-release Windows build for testing at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/24ox65hxy8w9bv51/artifacts.

**Comment by markummitchell** [comment]
Should be fixed now.

**Comment by k1moradi** [comment]
Thanks for the fast bug fix! May I have access to a testing mac release.

**Comment by markummitchell** [comment]
I tried reading  your sample file in OSX and found a problem. I will try to fix it for OSX too. I can give you a pre-release OSX build, but it will probably be much easier for me to debug since I can use the qtcreator integrated development environment (IDE).

**Comment by markummitchell** [comment]
The pre-version 10.9 fixes I had for the next version took care of the issue on my computer. You can try the pre-release for OSX at https://drive.google.com/drive/folders/0B5_zuEeNEicQY1U0dFRYWTZqblU

**Comment by k1moradi** [comment]
We tried to open files that are made with 10.7 version with 10.8 and 10.9-beta on mac and windows, but the program crashed again. Using the 10.7 version we could open them.

a sample file:
https://drive.google.com/open?id=1_JrYlqgJGqL5MwbgPeFD6QMNN4MV1xi-

**Comment by markummitchell** [comment]
The identifiers for the axis points were somehow corrupted. I have just uploaded a patched version at https://drive.google.com/drive/folders/0B5_zuEeNEicQY1U0dFRYWTZqblU that you can try.

**Comment by k1moradi** [comment]
We checked the latest version of the program and everything seems working normally. Thanks for the quick bug fix!
