### ISSUE TITLE
Bug in Cubic Spline Interpolation

### ISSUE THREAD

**Issue by kangaro0** [markummitchell/engauge-digitizer#288]
Hey,

I'm digitizing curves in pdf-files and the exported spline interpolation points do not seem to represent the correct curve. 

Here is a screenshot from Engauge Digitizer: https://ibb.co/nBgaMe
Here is a screenshot from Matlab: https://ibb.co/n785Me
And to check I used a online tool (Link: https://tools.timodenk.com/cubic-spline-interpolation), which result you can see here: https://ibb.co/fRzZEz

The problem is the deep ditch at moment x ~= 0.25

Greetings,
kangaro0

**Comment by markummitchell** [comment]
Hi, can I get a copy of the dig file? I will work on this.

**Comment by kangaro0** [comment]
Here you go: https://www.dropbox.com/s/9hvfp3dkowzz0lo/github.dig?dl=0
And thanks for the quick response!

**Comment by markummitchell** [comment]
Status - The current cubic spline fitting approach fits (x,y) points versus (t) where the t values are integers 0,1,... This approach nicely fits curve points for both Functions (=single-valued) and Relations (=not limited to single-valued).

I should mention that I have been investigating an alternative approach for Functions, in which (y) values are fitted versus (x) values, with no (t) values involved.  This guarantees single-valued behavior.

There are some issues with the current approach:
* For Functions, when 2 values have very similar x values it is easy to get an S shape with (x,y) versus (t) fitting, but the S shape is not a single-valued Function. This is the situation for the DIG file that produced issue #287. There is an S shape in the curve that is small and easily overlooked.
* One drawback in the current approach is that people are probably not expecting there to be an issue with multiple Y values for one X value, especially if they were expecting standard cubic spline fitting of (y) versus (x). So they are surprised with weird results when one X value gives a Y value for the bottom/middle/top part of the S, when they were expecting a Y value for some other part of the S
* The Export routine also gives unpredictable results for reasons explained in the previous bullet

There are some advantages to the current approach:
* It is what people are used to, and it is dangerous to change the default algorithm. Surprises like changing the current algorithm can really upset people - especially since the current algorithm works great as long as two points are not very close in X values
* The current algorithm is the same for both Functions and Relations. This simplicity is easier and less confusing for users.
* The current algorithm is much more well behaved when adjacent points are very close, compared to  the alternative approach of fitting (y) to (x). The alternative approach makes the entire fit (even far away) fluctuate wildly - it is like somebody made the Y scale 5 or 10 times larger!

I will rank the options by desirability as of the writing of this post:
* Desirable - Continue using the current (x,y) versus (t) curve fitting algorithm, but give some graphical feedback when the curve fit has become non-single-valued so the user can remove the conflict. This is low impact on the code, documentation and users, and continues to provide well-behaved curve fits.
* Less Desirable - Offer the new (which is (y) versus (x)) curve fitting as an option, with some sort of feedback telling users when they should consider switching. Considering the wild fluctuations the alternative approach can give, I am wondering about the benefit of this. And it is not so good for ease-of-use.
* Undesirable - Quietly replace the current algorithm with the new algorithm. This will upset users, some of whom run the software in batch mode and would have no notification that their numeric results had changed.

Thoughts?

**Comment by markummitchell** [comment]
I created a variation with the ability to use the single-valued splines that you were expecting. It had some problems:
1) When 2 or 3 successive points have a very high slope, that slope propagates outward which produces wide swings in amplitude over a fairly big area. This was disconcerting
2) When a point was shifted left or right so it was under or over another point, the infinite slope would make the slope infinite everywhere, making the curve line instantaneously disappear everywhere. This was also disconcerting. 

These new behaviors made adding the new mode less attractive. Since commit 3d3d524 should mitigate any confusion about the existing approach, I will not keep this new spline mode.
