### ISSUE TITLE
Exported data differ from the values in the digitizer

### ISSUE THREAD

**Issue by leosenko** [markummitchell/engauge-digitizer#303]
When I look at the geometry window, the values of the points are correct, when I export to csv or tsv, some of the values are incorrect (the ones with asterisk at the end).
![image](https://user-images.githubusercontent.com/3658579/51850863-a9562000-22f0-11e9-9a65-4c0973ccde8d.png)
The version is 10.11 from appImage.

It can be reproduced with [the following example](https://drive.google.com/file/d/1MeNQft6iElphwfiz4TzT-XFH7W2meWvo/view?usp=sharing):

**Comment by markummitchell** [comment]
Thanks for the input. I have been looking at this. The goal of the Geometry Window is to show the points with no interpolation to confuse things. The goal of the Export code is to do interpolation and extrapolation depending on the settings (with many complications due to linear versus log scales and other settings). Although the two blocks of code are very different, they give consistent results as long as there are no multi-valued sections of a function - which is the case for your example file. Right now I am thinking that it may be better to put red highlighting in the Geometry Window around the points attached to multi-valued function segments, along with some red warning text stating that exported points could be inconsistent. If you want to prevent this issue, you can switch the Curve Setting from Smooth to Straight.

**Comment by leosenko** [comment]
I do not understand what you mean by interpolation/extrapolation, if you are referring to axes mapping or to something else because the program cannot really provide any data without interpolation/extrapolation based on the axes points and I am not sure, how it is related to the multivalued nature of the function. The results, (x, y) of a point in the graph cannot be a function of (x,y) of another point. The end results is however, that even visually, the export is simply wrong. Maybe I am missing something, maybe the software is designed to fit a curve between points and not to give values of the points themselves though.
