### ISSUE TITLE
No automatic extensions when saving/exporting

### ISSUE THREAD

**Issue by sphh** [markummitchell/engauge-digitizer#311]
When I try to save a .dig file the file saving dialog leaves me without any clue about the appropriate filename extension. The same goes for the export dialog.

Would it be possible to append the right extension `.dig` to the filename if the filetype dropdown menu shows `Engauge Document` and no file extension is given in the `Name:` box? The same for the `Text CSV` and `Text TSV` exports?

**Comment by markummitchell** [comment]
In Linux and Windows the file extension appears when I run it. In OSX the file extension does not appear as shown in the following dialog:

![screen shot 2019-02-26 at 9 08 38 pm](https://user-images.githubusercontent.com/1624606/53467361-caeb1a00-3a0a-11e9-9b48-093ae806d8c4.png)

However, clicking on the down arrow at the top right brings up a 'Hide Extension' checkbox that you can change. This is standard OSX behavior so it probably better to not try to change it.

![screen shot 2019-02-26 at 9 11 38 pm](https://user-images.githubusercontent.com/1624606/53467455-24534900-3a0b-11e9-99b2-94f5616aec9a.png)

**Comment by sphh** [comment]
Linux Mint 19.1
Engauge Digitizer Version 10.11
installed from Linux Mint's flatpack

`File > Open...`:
![image](https://user-images.githubusercontent.com/4856462/53486475-1cd28500-3a89-11e9-8266-690ba0746cc5.png)

`File > Save as...`:
![image](https://user-images.githubusercontent.com/4856462/53486561-4e4b5080-3a89-11e9-99ad-0eeb354f2b5f.png)

`File > Export...`:
![image](https://user-images.githubusercontent.com/4856462/53486642-8e123800-3a89-11e9-8ebf-170fdb520922.png)

**Comment by markummitchell** [comment]
I had assumed the flatpak release was working fine since it tests out fine on the Linux build system. But, I was able to reproduce your problem in Cinnamon Linux. A quick investigation was not enough to identify the problem and solution. This will take more work. Thanks for identifying the problem.

**Comment by sphh** [comment]
Thanks for looking into it. If I can help in any way, please feel free to ask!

**Comment by markummitchell** [comment]
This problem seems to be happening outside of Engauge, with a workaround that may require more effort by users than just manually entering filenames themselves. The workaround steps, which switch Engauge from the GTK window manager to the KDE manager, are:

#sudo apt install plasma-discover-flatpak-backend     (one time step)
#sudo apt install xdg-desktop-portal-kde              (one time step)
#find /usr -name xdg-desktop-portal                   (find xdg-desktop-portal executable)
#find /usr -name xdg-desktop-portal-kde               (find xdg-desktop-portal-kde executable)
#kill xdg-desktop-portal
#kill xdg-desktop-portal-kde
#export XDG_CURRENT_DESKTOP=KDE
#/usr/.../xdg-desktop-portal-kde &                 (using path from earlier find command)
#/usr/.../xdg-desktop-portal &                        (using path from earlier find command)
#flatpak run io.github.markummitchell.Engauge_Digitizer

**Comment by sphh** [comment]
Thanks for figuring out a workaround. Since https://github.com/flatpak/xdg-desktop-portal-gtk/issues/191 mentions that they might solve the underlying bug, I might wait a bit ...
