### ISSUE TITLE
Crash when trying to access the export format option menu

### ISSUE THREAD

**Issue by k1moradi** [markummitchell/engauge-digitizer#323]
I use windows 10 64 bit. I was working on the following dig file.

https://1drv.ms/u/s!Ato0Wsph7iDRof9a-BzsFYzSvSc-CA

Whenever I click on "settings" --> "export format" program crashes.

Please check this report XML file.

https://1drv.ms/u/s!Ato0Wsph7iDRof9ZyXYt3HuLANOXqw

**Comment by markummitchell** [comment]
You can try a prerelease fix for Windows at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master. Pick x86 or x64 and then click on Artifacts at the top of the new web page. The 7z file can be downloaded and unzipped with tools like 7zip. 

The problem was that one curve had points and one curve did not. The code did not like trying to do interpolation on the curve that had no points. If no curves had points then export would have been safely skipped.

Thanks for the input. I will release this quickly after testing.

**Comment by k1moradi** [comment]
I confirm the problem is fixed. Thank you for the quick bug fix.
