### ISSUE TITLE
Import/replace triggers Save As

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge-digitizer#332]
It would be more convenient if import/replace of the image did not automatically trigger Save As but instead allowed Save.

Currently, this enhancement could cause loss of data if the currently opened file was not already given a unique name before the import/replace. However, this is easily solved by adding a new setting that could allow Save immediately after the import/replace. The default would offer the current behavior which tries to reduce the chances of loss of data.

**Comment by markummitchell** [comment]
@k1moradi  I am trying to understand the scenario. Can you describe the steps you are doing and what steps you would prefer?

**Comment by k1moradi** [comment]
I think import (image replace) function should allow saving the file instead of "save as". Two possible solutions come to my mind.
(1) Keeping the current behavior (opening save as menu) but suggesting the existing file name and path on save.
(2) After the successful import of new image opening a popup menu to ask the users if they want to "save as" or save.

**Comment by markummitchell** [comment]
I think I understand.  Can you try out the Windows 64 bit pre-release at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/osbbj6wprbju66eh/artifacts? I want to make this will solve the problem. There is also a 32 bit pre-release at https://ci.appveyor.com/project/markummitchell/engauge-digitizer/branch/master/job/yl92yi05eaq35rr8/artifacts

**Comment by k1moradi** [comment]
So, I tried both 32 and 64-bit builds. I opened a dig file and import (replaced) the image (no message box appeared), then I pressed the save. The program opened the save as menu suggesting the name of the new image file without remembering the original path. So I can say no it did not work because the program neither remembered the original dig file name nor the path it was saved already.

**Comment by markummitchell** [comment]
The default is the old besavior. You will need to change Image Replace Renames Document in Main Window settings

**Comment by k1moradi** [comment]
I see now. Thank you. I confirm it works.
