### ISSUE TITLE
Version 12.1 again does not support PDF import

### ISSUE THREAD

**Issue by bmbeyers** [markummitchell/engauge-digitizer#358]
I previously posted this issue for Version 10.4, and it was later fixed. I replied to that original issue thread with the text below, but that issue was marked as closed back in March of last year, so it might not provide any notifications any more. Just curious if I am missing something or if PDF import was once again removed. Thanks!

Not sure if it best to continue along this thread, or start a new one, but I noticed that version 12.1 (for Windows at least) again does not support PDF import.

_Originally posted by @bmbeyers in https://github.com/markummitchell/engauge-digitizer/issues/253#issuecomment-553043428_

**Comment by markummitchell** [comment]
Ok, I will try to restore it. I assume this is for the standard Windows version rather than Cygwin?

**Comment by bmbeyers** [comment]
Sorry for the delay in responding. I didn't use Cygwin. I obtained the file from the site below using instructions I found in another issue post.

https://ci.appveyor.com/project/markummitchell/engauge-digitizer

**Comment by markummitchell** [comment]
You were using a prerelease version that is built on the Appveyor server. Official releases are built on my own machine using a different procedure. I have verified that the upcoming releases will all contain pdf support. Thanks for the input since it helps to know that all the work involved in working with the pdf libraries is worthwhile.
